use register::mmio::ReadWrite;

#[repr(C)]
pub struct Parameters {
    pub memory_type: ReadWrite<u32>,

    pub pllm_input_divider: ReadWrite<u32>,
    pub pllm_feedback_divider: ReadWrite<u32>,
    pub pllm_stable_time: ReadWrite<u32>,
    pub pllm_setup_control: ReadWrite<u32>,
    pub pllm_post_divider: ReadWrite<u32>,
    pub pllm_kcp: ReadWrite<u32>,
    pub pllm_kvco: ReadWrite<u32>,
    pub emc_bct_spare0: ReadWrite<u32>,
    pub emc_bct_spare1: ReadWrite<u32>,
    pub emc_bct_spare2: ReadWrite<u32>,
    pub emc_bct_spare3: ReadWrite<u32>,
    pub emc_bct_spare4: ReadWrite<u32>,
    pub emc_bct_spare5: ReadWrite<u32>,
    pub emc_bct_spare6: ReadWrite<u32>,
    pub emc_bct_spare7: ReadWrite<u32>,
    pub emc_bct_spare8: ReadWrite<u32>,
    pub emc_bct_spare9: ReadWrite<u32>,
    pub emc_bct_spare10: ReadWrite<u32>,
    pub emc_bct_spare11: ReadWrite<u32>,
    pub emc_bct_spare12: ReadWrite<u32>,
    pub emc_bct_spare13: ReadWrite<u32>,

    pub emc_clock_source: ReadWrite<u32>,
    pub emc_clock_source_dll: ReadWrite<u32>,

    pub clk_rst_pllm_misc20_override: ReadWrite<u32>,
    pub clk_rst_pllm_misc20_override_enable: ReadWrite<u32>,
    pub clear_clock2_mc1: ReadWrite<u32>,

    pub emc_auto_cal_interval: ReadWrite<u32>,
    pub emc_auto_cal_config: ReadWrite<u32>,

    pub emc_auto_cal_config2: ReadWrite<u32>,

    pub emc_auto_cal_config3: ReadWrite<u32>,

    pub emc_auto_cal_config4: ReadWrite<u32>,
    pub emc_auto_cal_config5: ReadWrite<u32>,
    pub emc_auto_cal_config6: ReadWrite<u32>,
    pub emc_auto_cal_config7: ReadWrite<u32>,
    pub emc_auto_cal_config8: ReadWrite<u32>,
    pub emc_auto_cal_vref_sel0: ReadWrite<u32>,
    pub emc_auto_cal_vref_sel1: ReadWrite<u32>,

    pub emc_auto_cal_channel: ReadWrite<u32>,

    pub emc_pmacro_auto_cal_cfg0: ReadWrite<u32>,
    pub emc_pmacro_auto_cal_cfg1: ReadWrite<u32>,
    pub emc_pmacro_auto_cal_cfg2: ReadWrite<u32>,

    pub emc_pmacro_rx_term: ReadWrite<u32>,
    pub emc_pmacro_dq_tx_drive: ReadWrite<u32>,
    pub emc_pmacro_ca_tx_drive: ReadWrite<u32>,
    pub emc_pmacro_cmd_tx_drive: ReadWrite<u32>,
    pub emc_pmacro_auto_cal_common: ReadWrite<u32>,
    pub emc_pmacro_zcrtl: ReadWrite<u32>,

    pub emc_auto_cal_wait: ReadWrite<u32>,

    pub emc_xm2_comp_pad_ctrl: ReadWrite<u32>,
    pub emc_xm2_comp_pad_ctrl2: ReadWrite<u32>,
    pub emc_xm2_comp_pad_ctrl3: ReadWrite<u32>,

    pub emc_adr_cfg: ReadWrite<u32>,

    pub emc_pin_program_wait: ReadWrite<u32>,
    pub emc_pin_extra_wait: ReadWrite<u32>,

    pub emc_pin_gpio_enable: ReadWrite<u32>,
    pub emc_pin_gpio: ReadWrite<u32>,

    pub emc_timing_control_wait: ReadWrite<u32>,

    pub emc_rc: ReadWrite<u32>,
    pub emc_rfc: ReadWrite<u32>,

    pub emc_rfc_pb: ReadWrite<u32>,
    pub emc_ref_ctrl2: ReadWrite<u32>,

    pub emc_rfc_slr: ReadWrite<u32>,
    pub emc_ras: ReadWrite<u32>,
    pub emc_rp: ReadWrite<u32>,
    pub emc_r2r: ReadWrite<u32>,
    pub emc_w2w: ReadWrite<u32>,
    pub emc_r2w: ReadWrite<u32>,
    pub emc_w2r: ReadWrite<u32>,
    pub emc_r2p: ReadWrite<u32>,
    pub emc_w2p: ReadWrite<u32>,

    pub emc_tppd: ReadWrite<u32>,
    pub emc_ccdmw: ReadWrite<u32>,

    pub emc_rd_rcd: ReadWrite<u32>,
    pub emc_wr_rcd: ReadWrite<u32>,
    pub emc_rrd: ReadWrite<u32>,
    pub emc_rext: ReadWrite<u32>,
    pub emc_wext: ReadWrite<u32>,
    pub emc_wdv: ReadWrite<u32>,

    pub emc_wdv_chk: ReadWrite<u32>,
    pub emc_wsv: ReadWrite<u32>,
    pub emc_wev: ReadWrite<u32>,

    pub emc_wdv_mask: ReadWrite<u32>,

    pub emc_ws_duration: ReadWrite<u32>,
    pub emc_we_duration: ReadWrite<u32>,

    pub emc_quse: ReadWrite<u32>,
    pub emc_quse_width: ReadWrite<u32>,
    pub emc_ibdly: ReadWrite<u32>,

    pub emc_obdly: ReadWrite<u32>,

    pub emc_einput: ReadWrite<u32>,
    pub emc_einput_duration: ReadWrite<u32>,
    pub emc_puterm_extra: ReadWrite<u32>,
    pub emc_puterm_width: ReadWrite<u32>,

    pub emc_qrst: ReadWrite<u32>,
    pub emc_qsafe: ReadWrite<u32>,
    pub emc_rdv: ReadWrite<u32>,
    pub emc_rdv_mask: ReadWrite<u32>,

    pub emc_rdv_early: ReadWrite<u32>,
    pub emc_rdv_early_mask: ReadWrite<u32>,

    pub emc_qpop: ReadWrite<u32>,

    pub emc_refresh: ReadWrite<u32>,
    pub emc_burst_refresh_num: ReadWrite<u32>,
    pub emc_prerefresh_req_cnt: ReadWrite<u32>,
    pub emc_pdex2wr: ReadWrite<u32>,
    pub emc_pdex2rd: ReadWrite<u32>,
    pub emc_pchg2pden: ReadWrite<u32>,
    pub emc_act2pden: ReadWrite<u32>,
    pub emc_ar2pden: ReadWrite<u32>,
    pub emc_rw2pden: ReadWrite<u32>,

    pub emc_cke2pden: ReadWrite<u32>,
    pub emc_pdex2che: ReadWrite<u32>,
    pub emc_pdex2mrr: ReadWrite<u32>,

    pub emc_txsr: ReadWrite<u32>,
    pub emc_txsr_dll: ReadWrite<u32>,
    pub emc_tcke: ReadWrite<u32>,
    pub emc_tckesr: ReadWrite<u32>,
    pub emc_tpd: ReadWrite<u32>,
    pub emc_tfaw: ReadWrite<u32>,
    pub emc_trpab: ReadWrite<u32>,
    pub emc_tclkstable: ReadWrite<u32>,
    pub emc_tclkstop: ReadWrite<u32>,
    pub emc_trefbw: ReadWrite<u32>,

    pub emc_fbio_cfg5: ReadWrite<u32>,
    pub emc_fbio_cfg7: ReadWrite<u32>,
    pub emc_fbio_cfg8: ReadWrite<u32>,

    pub emc_cmd_mapping_cmd0_0: ReadWrite<u32>,
    pub emc_cmd_mapping_cmd0_1: ReadWrite<u32>,
    pub emc_cmd_mapping_cmd0_2: ReadWrite<u32>,
    pub emc_cmd_mapping_cmd1_0: ReadWrite<u32>,
    pub emc_cmd_mapping_cmd1_1: ReadWrite<u32>,
    pub emc_cmd_mapping_cmd1_2: ReadWrite<u32>,
    pub emc_cmd_mapping_cmd2_0: ReadWrite<u32>,
    pub emc_cmd_mapping_cmd2_1: ReadWrite<u32>,
    pub emc_cmd_mapping_cmd2_2: ReadWrite<u32>,
    pub emc_cmd_mapping_cmd3_0: ReadWrite<u32>,
    pub emc_cmd_mapping_cmd3_1: ReadWrite<u32>,
    pub emc_cmd_mapping_cmd3_2: ReadWrite<u32>,
    pub emc_cmd_mapping_byte: ReadWrite<u32>,

    pub emc_fbio_spare: ReadWrite<u32>,

    pub emc_cfg_rsv: ReadWrite<u32>,

    pub emc_mrs: ReadWrite<u32>,
    pub emc_emrs: ReadWrite<u32>,
    pub emc_emrs2: ReadWrite<u32>,
    pub emc_emrs3: ReadWrite<u32>,
    pub emc_mrw1: ReadWrite<u32>,
    pub emc_mrw2: ReadWrite<u32>,
    pub emc_mrw3: ReadWrite<u32>,
    pub emc_mrw4: ReadWrite<u32>,

    pub emc_mrw6: ReadWrite<u32>,
    pub emc_mrw8: ReadWrite<u32>,
    pub emc_mrw9: ReadWrite<u32>,
    pub emc_mrw10: ReadWrite<u32>,
    pub emc_mrw12: ReadWrite<u32>,
    pub emc_mrw13: ReadWrite<u32>,
    pub emc_mrw14: ReadWrite<u32>,

    pub emc_mrw_extra: ReadWrite<u32>,
    pub emc_warm_boot_mrw_extra: ReadWrite<u32>,
    pub emc_warm_boot_extramode_reg_write_enable: ReadWrite<u32>,
    pub emc_extramode_reg_write_enable: ReadWrite<u32>,

    pub emc_mrw_reset_command: ReadWrite<u32>,
    pub emc_mrw_reset_ninit_wait: ReadWrite<u32>,
    pub emc_mrs_wait_cnt: ReadWrite<u32>,
    pub emc_mrs_wait_cnt2: ReadWrite<u32>,

    pub emc_cfg: ReadWrite<u32>,
    pub emc_cfg2: ReadWrite<u32>,
    pub emc_cfg_pipe: ReadWrite<u32>,

    pub emc_cfg_pipe_clk: ReadWrite<u32>,
    pub emc_fdpd_ctrl_cmd_no_ramp: ReadWrite<u32>,
    pub emc_cfg_update: ReadWrite<u32>,

    pub emc_dbg: ReadWrite<u32>,

    pub emc_dbg_write_mux: ReadWrite<u32>,

    pub emc_cmd_q: ReadWrite<u32>,
    pub emc_mc2emc_q: ReadWrite<u32>,
    pub emc_dyn_self_ref_control: ReadWrite<u32>,

    pub ahb_arbitration_xbar_ctrl_meminit_done: ReadWrite<u32>,

    pub emc_cfg_dig_dll: ReadWrite<u32>,
    pub emc_cfg_dig_dll_1: ReadWrite<u32>,

    pub emc_cfg_dig_dll_period: ReadWrite<u32>,
    pub emc_dev_select: ReadWrite<u32>,

    pub emc_sel_dpd_ctrl: ReadWrite<u32>,

    pub emc_fdpd_ctrl_dq: ReadWrite<u32>,
    pub emc_fdpd_ctrl_cmd: ReadWrite<u32>,
    pub emc_pmacro_ib_vref_dq_0: ReadWrite<u32>,
    pub emc_pmacro_ib_vref_dq_1: ReadWrite<u32>,
    pub emc_pmacro_ib_vref_dqs_0: ReadWrite<u32>,
    pub emc_pmacro_ib_vref_dqs_1: ReadWrite<u32>,
    pub emc_pmacro_ib_rxrt: ReadWrite<u32>,
    pub emc_cfg_pipe1: ReadWrite<u32>,
    pub emc_cfg_pipe2: ReadWrite<u32>,

    pub emc_pmacro_quse_ddll_rank0_0: ReadWrite<u32>,
    pub emc_pmacro_quse_ddll_rank0_1: ReadWrite<u32>,
    pub emc_pmacro_quse_ddll_rank0_2: ReadWrite<u32>,
    pub emc_pmacro_quse_ddll_rank0_3: ReadWrite<u32>,
    pub emc_pmacro_quse_ddll_rank0_4: ReadWrite<u32>,
    pub emc_pmacro_quse_ddll_rank0_5: ReadWrite<u32>,
    pub emc_pmacro_quse_ddll_rank1_0: ReadWrite<u32>,
    pub emc_pmacro_quse_ddll_rank1_1: ReadWrite<u32>,
    pub emc_pmacro_quse_ddll_rank1_2: ReadWrite<u32>,
    pub emc_pmacro_quse_ddll_rank1_3: ReadWrite<u32>,
    pub emc_pmacro_quse_ddll_rank1_4: ReadWrite<u32>,
    pub emc_pmacro_quse_ddll_rank1_5: ReadWrite<u32>,

    pub emc_pmacro_ob_ddll_long_dq_rank0_0: ReadWrite<u32>,
    pub emc_pmacro_ob_ddll_long_dq_rank0_1: ReadWrite<u32>,
    pub emc_pmacro_ob_ddll_long_dq_rank0_2: ReadWrite<u32>,
    pub emc_pmacro_ob_ddll_long_dq_rank0_3: ReadWrite<u32>,
    pub emc_pmacro_ob_ddll_long_dq_rank0_4: ReadWrite<u32>,
    pub emc_pmacro_ob_ddll_long_dq_rank0_5: ReadWrite<u32>,
    pub emc_pmacro_ob_ddll_long_dq_rank1_0: ReadWrite<u32>,
    pub emc_pmacro_ob_ddll_long_dq_rank1_1: ReadWrite<u32>,
    pub emc_pmacro_ob_ddll_long_dq_rank1_2: ReadWrite<u32>,
    pub emc_pmacro_ob_ddll_long_dq_rank1_3: ReadWrite<u32>,
    pub emc_pmacro_ob_ddll_long_dq_rank1_4: ReadWrite<u32>,
    pub emc_pmacro_ob_ddll_long_dq_rank1_5: ReadWrite<u32>,

    pub emc_pmacro_ob_ddll_long_dqs_rank0_0: ReadWrite<u32>,
    pub emc_pmacro_ob_ddll_long_dqs_rank0_1: ReadWrite<u32>,
    pub emc_pmacro_ob_ddll_long_dqs_rank0_2: ReadWrite<u32>,
    pub emc_pmacro_ob_ddll_long_dqs_rank0_3: ReadWrite<u32>,
    pub emc_pmacro_ob_ddll_long_dqs_rank0_4: ReadWrite<u32>,
    pub emc_pmacro_ob_ddll_long_dqs_rank0_5: ReadWrite<u32>,
    pub emc_pmacro_ob_ddll_long_dqs_rank1_0: ReadWrite<u32>,
    pub emc_pmacro_ob_ddll_long_dqs_rank1_1: ReadWrite<u32>,
    pub emc_pmacro_ob_ddll_long_dqs_rank1_2: ReadWrite<u32>,
    pub emc_pmacro_ob_ddll_long_dqs_rank1_3: ReadWrite<u32>,
    pub emc_pmacro_ob_ddll_long_dqs_rank1_4: ReadWrite<u32>,
    pub emc_pmacro_ob_ddll_long_dqs_rank1_5: ReadWrite<u32>,

    pub emc_pmacro_ib_ddll_long_dqs_rank0_0: ReadWrite<u32>,
    pub emc_pmacro_ib_ddll_long_dqs_rank0_1: ReadWrite<u32>,
    pub emc_pmacro_ib_ddll_long_dqs_rank0_2: ReadWrite<u32>,
    pub emc_pmacro_ib_ddll_long_dqs_rank0_3: ReadWrite<u32>,
    pub emc_pmacro_ib_ddll_long_dqs_rank1_0: ReadWrite<u32>,
    pub emc_pmacro_ib_ddll_long_dqs_rank1_1: ReadWrite<u32>,
    pub emc_pmacro_ib_ddll_long_dqs_rank1_2: ReadWrite<u32>,
    pub emc_pmacro_ib_ddll_long_dqs_rank1_3: ReadWrite<u32>,

    pub emc_pmacro_ddll_long_cmd_0: ReadWrite<u32>,
    pub emc_pmacro_ddll_long_cmd_1: ReadWrite<u32>,
    pub emc_pmacro_ddll_long_cmd_2: ReadWrite<u32>,
    pub emc_pmacro_ddll_long_cmd_3: ReadWrite<u32>,
    pub emc_pmacro_ddll_long_cmd_4: ReadWrite<u32>,
    pub emc_pmacro_ddll_short_cmd_0: ReadWrite<u32>,
    pub emc_pmacro_ddll_short_cmd_1: ReadWrite<u32>,
    pub emc_pmacro_ddll_short_cmd_2: ReadWrite<u32>,

    pub warm_boot_wait: ReadWrite<u32>,

    pub emc_odt_write: ReadWrite<u32>,

    pub emc_zcal_interval: ReadWrite<u32>,
    pub emc_zcal_wait_cnt: ReadWrite<u32>,
    pub emc_zcal_mrw_cmd: ReadWrite<u32>,

    pub emc_mrs_reset_dll: ReadWrite<u32>,
    pub emc_zcal_init_dev0: ReadWrite<u32>,
    pub emc_zcal_init_dev1: ReadWrite<u32>,
    pub emc_zcal_init_wait: ReadWrite<u32>,
    pub emc_zcal_warm_cold_boot_enables: ReadWrite<u32>,

    pub emc_mrw_lpddr2zcal_warm_boot: ReadWrite<u32>,
    pub emc_zqcal_ddr3_warm_boot: ReadWrite<u32>,

    pub emc_zqcal_lpddr4_warm_boot: ReadWrite<u32>,

    pub emc_zcal_warm_boot_wait: ReadWrite<u32>,
    pub emc_mrs_warm_boot_enable: ReadWrite<u32>,
    pub emc_mrs_reset_dll_wait: ReadWrite<u32>,
    pub emc_mrs_extra: ReadWrite<u32>,
    pub emc_warm_boot_mrs_extra: ReadWrite<u32>,
    pub emc_emrs_ddr2_dll_enable: ReadWrite<u32>,
    pub emc_mrs_ddr2_dll_reset: ReadWrite<u32>,
    pub emc_emrs_ddr2_ocd_calib: ReadWrite<u32>,
    pub emc_ddr2_wait: ReadWrite<u32>,
    pub emc_clken_override: ReadWrite<u32>,
    pub emc_extra_refresh_num: ReadWrite<u32>,
    pub emc_clken_override_allwarm_boot: ReadWrite<u32>,
    pub mc_clken_override_allwarm_boot: ReadWrite<u32>,
    pub emc_cfg_dig_dll_period_warm_boot: ReadWrite<u32>,

    pub pmc_vddp_sel: ReadWrite<u32>,
    pub pmc_vddp_sel_wait: ReadWrite<u32>,
    pub pmc_ddr_pwr: ReadWrite<u32>,
    pub pmc_ddr_cfg: ReadWrite<u32>,
    pub pmc_io_dpd3_req: ReadWrite<u32>,
    pub pmc_io_dpd3_req_wait: ReadWrite<u32>,

    pub pmc_io_dpd4_req_wait: ReadWrite<u32>,

    pub pmc_reg_short: ReadWrite<u32>,
    pub pmc_no_io_power: ReadWrite<u32>,

    pub pmc_ddr_ctrl_wait: ReadWrite<u32>,
    pub pmc_ddr_ctrl: ReadWrite<u32>,

    pub emc_acpd_control: ReadWrite<u32>,

    pub emc_swizzle_rank0_byte0: ReadWrite<u32>,
    pub emc_swizzle_rank0_byte1: ReadWrite<u32>,
    pub emc_swizzle_rank0_byte2: ReadWrite<u32>,
    pub emc_swizzle_rank0_byte3: ReadWrite<u32>,
    pub emc_swizzle_rank1_byte0: ReadWrite<u32>,
    pub emc_swizzle_rank1_byte1: ReadWrite<u32>,
    pub emc_swizzle_rank1_byte2: ReadWrite<u32>,
    pub emc_swizzle_rank1_byte3: ReadWrite<u32>,

    pub emc_txdsrvttgen: ReadWrite<u32>,

    pub emc_data_brlshft0: ReadWrite<u32>,
    pub emc_data_brlshft1: ReadWrite<u32>,

    pub emc_dqs_brlshft0: ReadWrite<u32>,
    pub emc_dqs_brlshft1: ReadWrite<u32>,

    pub emc_cmd_brlshft0: ReadWrite<u32>,
    pub emc_cmd_brlshft1: ReadWrite<u32>,
    pub emc_cmd_brlshft2: ReadWrite<u32>,
    pub emc_cmd_brlshft3: ReadWrite<u32>,

    pub emc_quse_brlshft0: ReadWrite<u32>,
    pub emc_quse_brlshft1: ReadWrite<u32>,
    pub emc_quse_brlshft2: ReadWrite<u32>,
    pub emc_quse_brlshft3: ReadWrite<u32>,

    pub emc_dll_cfg0: ReadWrite<u32>,
    pub emc_dll_cfg1: ReadWrite<u32>,

    pub emc_pmc_scratch1: ReadWrite<u32>,
    pub emc_pmc_scratch2: ReadWrite<u32>,
    pub emc_pmc_scratch3: ReadWrite<u32>,

    pub emc_pmacro_pad_cfg_ctrl: ReadWrite<u32>,

    pub emc_pmacro_vttgen_ctrl0: ReadWrite<u32>,
    pub emc_pmacro_vttgen_ctrl1: ReadWrite<u32>,
    pub emc_pmacro_vttgen_ctrl2: ReadWrite<u32>,

    pub emc_pmacro_brick_ctrl_rfu1: ReadWrite<u32>,
    pub emc_pmacro_cmd_brick_ctrl_fdpd: ReadWrite<u32>,
    pub emc_pmacro_brick_ctrl_rfu2: ReadWrite<u32>,
    pub emc_pmacro_data_brick_ctrl_fdpd: ReadWrite<u32>,
    pub emc_pmacro_bg_bias_ctrl0: ReadWrite<u32>,
    pub emc_pmacro_data_pad_rx_ctrl: ReadWrite<u32>,
    pub emc_pmacro_cmd_pad_rx_ctrl: ReadWrite<u32>,
    pub emc_pmacro_data_rx_term_mode: ReadWrite<u32>,
    pub emc_pmacro_cmd_rx_term_mode: ReadWrite<u32>,
    pub emc_pmacro_data_pad_tx_ctrl: ReadWrite<u32>,
    pub emc_pmacro_common_pad_tx_ctrl: ReadWrite<u32>,
    pub emc_pmacro_cmd_pad_tx_ctrl: ReadWrite<u32>,
    pub emc_cfg3: ReadWrite<u32>,

    pub emc_pmacro_tx_pwrd0: ReadWrite<u32>,
    pub emc_pmacro_tx_pwrd1: ReadWrite<u32>,
    pub emc_pmacro_tx_pwrd2: ReadWrite<u32>,
    pub emc_pmacro_tx_pwrd3: ReadWrite<u32>,
    pub emc_pmacro_tx_pwrd4: ReadWrite<u32>,
    pub emc_pmacro_tx_pwrd5: ReadWrite<u32>,

    pub emc_config_sample_delay: ReadWrite<u32>,

    pub emc_pmacro_brick_mapping0: ReadWrite<u32>,
    pub emc_pmacro_brick_mapping1: ReadWrite<u32>,
    pub emc_pmacro_brick_mapping2: ReadWrite<u32>,

    pub emc_pmacro_tx_sel_clk_src0: ReadWrite<u32>,
    pub emc_pmacro_tx_sel_clk_src1: ReadWrite<u32>,
    pub emc_pmacro_tx_sel_clk_src2: ReadWrite<u32>,
    pub emc_pmacro_tx_sel_clk_src3: ReadWrite<u32>,
    pub emc_pmacro_tx_sel_clk_src4: ReadWrite<u32>,
    pub emc_pmacro_tx_sel_clk_src5: ReadWrite<u32>,

    pub emc_pmacro_ddll_bypass: ReadWrite<u32>,

    pub emc_pmacro_ddll_pwrd0: ReadWrite<u32>,
    pub emc_pmacro_ddll_pwrd1: ReadWrite<u32>,
    pub emc_pmacro_ddll_pwrd2: ReadWrite<u32>,

    pub emc_pmacro_cmd_ctrl0: ReadWrite<u32>,
    pub emc_pmacro_cmd_ctrl1: ReadWrite<u32>,
    pub emc_pmacro_cmd_ctrl2: ReadWrite<u32>,

    pub mc_emem_adr_cfg: ReadWrite<u32>,
    pub mc_emem_adr_cfg_dev0: ReadWrite<u32>,
    pub mc_emem_adr_cfg_dev1: ReadWrite<u32>,

    pub mc_emem_adr_cfg_channel_mask: ReadWrite<u32>,

    pub mc_emem_adr_cfg_bank_mask0: ReadWrite<u32>,
    pub mc_emem_adr_cfg_bank_mask1: ReadWrite<u32>,
    pub mc_emem_adr_cfg_bank_mask2: ReadWrite<u32>,

    pub mc_emem_cfg: ReadWrite<u32>,

    pub mc_emem_arb_cfg: ReadWrite<u32>,
    pub mc_emem_arb_outstanding_req: ReadWrite<u32>,

    pub emc_emem_arb_refpb_hp_ctrl: ReadWrite<u32>,
    pub emc_emem_arb_refpb_bank_ctrl: ReadWrite<u32>,

    pub mc_emem_arb_timing_rcd: ReadWrite<u32>,
    pub mc_emem_arb_timing_rp: ReadWrite<u32>,
    pub mc_emem_arb_timing_rc: ReadWrite<u32>,
    pub mc_emem_arb_timing_ras: ReadWrite<u32>,
    pub mc_emem_arb_timing_faw: ReadWrite<u32>,
    pub mc_emem_arb_timing_rrd: ReadWrite<u32>,
    pub mc_emem_arb_timing_rap2pre: ReadWrite<u32>,
    pub mc_emem_arb_timing_wap2pre: ReadWrite<u32>,
    pub mc_emem_arb_timing_r2r: ReadWrite<u32>,
    pub mc_emem_arb_timing_w2w: ReadWrite<u32>,
    pub mc_emem_arb_timing_r2w: ReadWrite<u32>,
    pub mc_emem_arb_timing_w2r: ReadWrite<u32>,

    pub mc_emem_arb_timing_rfcpb: ReadWrite<u32>,

    pub mc_emem_arb_da_turns: ReadWrite<u32>,
    pub mc_emem_arb_da_covers: ReadWrite<u32>,
    pub mc_emem_arb_misc0: ReadWrite<u32>,
    pub mc_emem_arb_misc1: ReadWrite<u32>,
    pub mc_emem_arb_misc2: ReadWrite<u32>,

    pub mc_emem_arb_ring1_throttle: ReadWrite<u32>,
    pub mc_emem_arb_override: ReadWrite<u32>,
    pub mc_emem_arb_override1: ReadWrite<u32>,
    pub mc_emem_arb_rsv: ReadWrite<u32>,

    pub mc_da_cfg0: ReadWrite<u32>,
    pub mc_emem_arb_timing_ccdmw: ReadWrite<u32>,

    pub mc_clken_override: ReadWrite<u32>,

    pub mc_stat_control: ReadWrite<u32>,
    pub mc_video_protect_bom: ReadWrite<u32>,
    pub mc_video_protect_bom_adr_hi: ReadWrite<u32>,
    pub mc_video_protect_size_mb: ReadWrite<u32>,
    pub mc_video_protect_vpr_override: ReadWrite<u32>,
    pub mc_video_protect_vpr_override1: ReadWrite<u32>,
    pub mc_video_protect_gpu_override0: ReadWrite<u32>,
    pub mc_video_protect_gpu_override1: ReadWrite<u32>,
    pub mc_sec_carveout_bom: ReadWrite<u32>,
    pub mc_sec_carveout_adr_hi: ReadWrite<u32>,
    pub mc_sec_carveout_size_mb: ReadWrite<u32>,
    pub mc_video_protect_write_access: ReadWrite<u32>,
    pub mc_sec_carveout_protect_write_access: ReadWrite<u32>,

    pub mc_generalized_carveout1_bom: ReadWrite<u32>,
    pub mc_generalized_carveout1_bom_hi: ReadWrite<u32>,
    pub mc_generalized_carveout1_size_128kb: ReadWrite<u32>,
    pub mc_generalized_carveout1_access0: ReadWrite<u32>,
    pub mc_generalized_carveout1_access1: ReadWrite<u32>,
    pub mc_generalized_carveout1_access2: ReadWrite<u32>,
    pub mc_generalized_carveout1_access3: ReadWrite<u32>,
    pub mc_generalized_carveout1_access4: ReadWrite<u32>,
    pub mc_generalized_carveout1_force_internal_access0: ReadWrite<u32>,
    pub mc_generalized_carveout1_force_internal_access1: ReadWrite<u32>,
    pub mc_generalized_carveout1_force_internal_access2: ReadWrite<u32>,
    pub mc_generalized_carveout1_force_internal_access3: ReadWrite<u32>,
    pub mc_generalized_carveout1_force_internal_access4: ReadWrite<u32>,
    pub mc_generalized_carveout1_cfg0: ReadWrite<u32>,

    pub mc_generalized_carveout2_bom: ReadWrite<u32>,
    pub mc_generalized_carveout2_bom_hi: ReadWrite<u32>,
    pub mc_generalized_carveout2_size_128kb: ReadWrite<u32>,
    pub mc_generalized_carveout2_access0: ReadWrite<u32>,
    pub mc_generalized_carveout2_access1: ReadWrite<u32>,
    pub mc_generalized_carveout2_access2: ReadWrite<u32>,
    pub mc_generalized_carveout2_access3: ReadWrite<u32>,
    pub mc_generalized_carveout2_access4: ReadWrite<u32>,
    pub mc_generalized_carveout2_force_internal_access0: ReadWrite<u32>,
    pub mc_generalized_carveout2_force_internal_access1: ReadWrite<u32>,
    pub mc_generalized_carveout2_force_internal_access2: ReadWrite<u32>,
    pub mc_generalized_carveout2_force_internal_access3: ReadWrite<u32>,
    pub mc_generalized_carveout2_force_internal_access4: ReadWrite<u32>,
    pub mc_generalized_carveout2_cfg0: ReadWrite<u32>,

    pub mc_generalized_carveout3_bom: ReadWrite<u32>,
    pub mc_generalized_carveout3_bom_hi: ReadWrite<u32>,
    pub mc_generalized_carveout3_size_128kb: ReadWrite<u32>,
    pub mc_generalized_carveout3_access0: ReadWrite<u32>,
    pub mc_generalized_carveout3_access1: ReadWrite<u32>,
    pub mc_generalized_carveout3_access2: ReadWrite<u32>,
    pub mc_generalized_carveout3_access3: ReadWrite<u32>,
    pub mc_generalized_carveout3_access4: ReadWrite<u32>,
    pub mc_generalized_carveout3_force_internal_access0: ReadWrite<u32>,
    pub mc_generalized_carveout3_force_internal_access1: ReadWrite<u32>,
    pub mc_generalized_carveout3_force_internal_access2: ReadWrite<u32>,
    pub mc_generalized_carveout3_force_internal_access3: ReadWrite<u32>,
    pub mc_generalized_carveout3_force_internal_access4: ReadWrite<u32>,
    pub mc_generalized_carveout3_cfg0: ReadWrite<u32>,

    pub mc_generalized_carveout4_bom: ReadWrite<u32>,
    pub mc_generalized_carveout4_bom_hi: ReadWrite<u32>,
    pub mc_generalized_carveout4_size_128kb: ReadWrite<u32>,
    pub mc_generalized_carveout4_access0: ReadWrite<u32>,
    pub mc_generalized_carveout4_access1: ReadWrite<u32>,
    pub mc_generalized_carveout4_access2: ReadWrite<u32>,
    pub mc_generalized_carveout4_access3: ReadWrite<u32>,
    pub mc_generalized_carveout4_access4: ReadWrite<u32>,
    pub mc_generalized_carveout4_force_internal_access0: ReadWrite<u32>,
    pub mc_generalized_carveout4_force_internal_access1: ReadWrite<u32>,
    pub mc_generalized_carveout4_force_internal_access2: ReadWrite<u32>,
    pub mc_generalized_carveout4_force_internal_access3: ReadWrite<u32>,
    pub mc_generalized_carveout4_force_internal_access4: ReadWrite<u32>,
    pub mc_generalized_carveout4_cfg0: ReadWrite<u32>,

    pub mc_generalized_carveout5_bom: ReadWrite<u32>,
    pub mc_generalized_carveout5_bom_hi: ReadWrite<u32>,
    pub mc_generalized_carveout5_size_128kb: ReadWrite<u32>,
    pub mc_generalized_carveout5_access0: ReadWrite<u32>,
    pub mc_generalized_carveout5_access1: ReadWrite<u32>,
    pub mc_generalized_carveout5_access2: ReadWrite<u32>,
    pub mc_generalized_carveout5_access3: ReadWrite<u32>,
    pub mc_generalized_carveout5_access4: ReadWrite<u32>,
    pub mc_generalized_carveout5_force_internal_access0: ReadWrite<u32>,
    pub mc_generalized_carveout5_force_internal_access1: ReadWrite<u32>,
    pub mc_generalized_carveout5_force_internal_access2: ReadWrite<u32>,
    pub mc_generalized_carveout5_force_internal_access3: ReadWrite<u32>,
    pub mc_generalized_carveout5_force_internal_access4: ReadWrite<u32>,
    pub mc_generalized_carveout5_cfg0: ReadWrite<u32>,

    pub emc_ca_training_enable: ReadWrite<u32>,
    pub swizzle_rank_byte_encode: ReadWrite<u32>,
    pub boot_rom_patch_control: ReadWrite<u32>,
    pub boot_rom_patch_data: ReadWrite<u32>,

    pub mc_mts_carveout_bom: ReadWrite<u32>,
    pub mc_mts_carveout_adr_hi: ReadWrite<u32>,
    pub mc_mts_carveout_size_mb: ReadWrite<u32>,
    pub mc_mts_carveout_reg_ctrl: ReadWrite<u32>,
}
