#[repr(C)]
#[derive(Clone, Copy)]
pub struct Parameters {
    pub memory_type: u32,

    pub pllm_input_divider: u32,
    pub pllm_feedback_divider: u32,
    pub pllm_stable_time: u32,
    pub pllm_setup_control: u32,
    pub pllm_post_divider: u32,
    pub pllm_kcp: u32,
    pub pllm_kvco: u32,
    pub emc_bct_spare0: u32,
    pub emc_bct_spare1: u32,
    pub emc_bct_spare2: u32,
    pub emc_bct_spare3: u32,
    pub emc_bct_spare4: u32,
    pub emc_bct_spare5: u32,
    pub emc_bct_spare6: u32,
    pub emc_bct_spare7: u32,
    pub emc_bct_spare8: u32,
    pub emc_bct_spare9: u32,
    pub emc_bct_spare10: u32,
    pub emc_bct_spare11: u32,
    pub emc_bct_spare12: u32,
    pub emc_bct_spare13: u32,

    pub emc_clock_source: u32,
    pub emc_clock_source_dll: u32,

    pub clk_rst_pllm_misc20_override: u32,
    pub clk_rst_pllm_misc20_override_enable: u32,
    pub clear_clock2_mc1: u32,

    pub emc_auto_cal_interval: u32,
    pub emc_auto_cal_config: u32,

    pub emc_auto_cal_config2: u32,

    pub emc_auto_cal_config3: u32,

    pub emc_auto_cal_config4: u32,
    pub emc_auto_cal_config5: u32,
    pub emc_auto_cal_config6: u32,
    pub emc_auto_cal_config7: u32,
    pub emc_auto_cal_config8: u32,
    pub emc_auto_cal_vref_sel0: u32,
    pub emc_auto_cal_vref_sel1: u32,

    pub emc_auto_cal_channel: u32,

    pub emc_pmacro_auto_cal_cfg0: u32,
    pub emc_pmacro_auto_cal_cfg1: u32,
    pub emc_pmacro_auto_cal_cfg2: u32,

    pub emc_pmacro_rx_term: u32,
    pub emc_pmacro_dq_tx_drive: u32,
    pub emc_pmacro_ca_tx_drive: u32,
    pub emc_pmacro_cmd_tx_drive: u32,
    pub emc_pmacro_auto_cal_common: u32,
    pub emc_pmacro_zcrtl: u32,

    pub emc_auto_cal_wait: u32,

    pub emc_xm2_comp_pad_ctrl: u32,
    pub emc_xm2_comp_pad_ctrl2: u32,
    pub emc_xm2_comp_pad_ctrl3: u32,

    pub emc_adr_cfg: u32,

    pub emc_pin_program_wait: u32,
    pub emc_pin_extra_wait: u32,

    pub emc_pin_gpio_enable: u32,
    pub emc_pin_gpio: u32,

    pub emc_timing_control_wait: u32,

    pub emc_rc: u32,
    pub emc_rfc: u32,

    pub emc_rfc_pb: u32,
    pub emc_ref_ctrl2: u32,

    pub emc_rfc_slr: u32,
    pub emc_ras: u32,
    pub emc_rp: u32,
    pub emc_r2r: u32,
    pub emc_w2w: u32,
    pub emc_r2w: u32,
    pub emc_w2r: u32,
    pub emc_r2p: u32,
    pub emc_w2p: u32,

    pub emc_tppd: u32,
    pub emc_ccdmw: u32,

    pub emc_rd_rcd: u32,
    pub emc_wr_rcd: u32,
    pub emc_rrd: u32,
    pub emc_rext: u32,
    pub emc_wext: u32,
    pub emc_wdv: u32,

    pub emc_wdv_chk: u32,
    pub emc_wsv: u32,
    pub emc_wev: u32,

    pub emc_wdv_mask: u32,

    pub emc_ws_duration: u32,
    pub emc_we_duration: u32,

    pub emc_quse: u32,
    pub emc_quse_width: u32,
    pub emc_ibdly: u32,

    pub emc_obdly: u32,

    pub emc_einput: u32,
    pub emc_einput_duration: u32,
    pub emc_puterm_extra: u32,
    pub emc_puterm_width: u32,

    pub emc_qrst: u32,
    pub emc_qsafe: u32,
    pub emc_rdv: u32,
    pub emc_rdv_mask: u32,

    pub emc_rdv_early: u32,
    pub emc_rdv_early_mask: u32,

    pub emc_qpop: u32,

    pub emc_refresh: u32,
    pub emc_burst_refresh_num: u32,
    pub emc_prerefresh_req_cnt: u32,
    pub emc_pdex2wr: u32,
    pub emc_pdex2rd: u32,
    pub emc_pchg2pden: u32,
    pub emc_act2pden: u32,
    pub emc_ar2pden: u32,
    pub emc_rw2pden: u32,

    pub emc_cke2pden: u32,
    pub emc_pdex2che: u32,
    pub emc_pdex2mrr: u32,

    pub emc_txsr: u32,
    pub emc_txsr_dll: u32,
    pub emc_tcke: u32,
    pub emc_tckesr: u32,
    pub emc_tpd: u32,
    pub emc_tfaw: u32,
    pub emc_trpab: u32,
    pub emc_tclkstable: u32,
    pub emc_tclkstop: u32,
    pub emc_trefbw: u32,

    pub emc_fbio_cfg5: u32,
    pub emc_fbio_cfg7: u32,
    pub emc_fbio_cfg8: u32,

    pub emc_cmd_mapping_cmd0_0: u32,
    pub emc_cmd_mapping_cmd0_1: u32,
    pub emc_cmd_mapping_cmd0_2: u32,
    pub emc_cmd_mapping_cmd1_0: u32,
    pub emc_cmd_mapping_cmd1_1: u32,
    pub emc_cmd_mapping_cmd1_2: u32,
    pub emc_cmd_mapping_cmd2_0: u32,
    pub emc_cmd_mapping_cmd2_1: u32,
    pub emc_cmd_mapping_cmd2_2: u32,
    pub emc_cmd_mapping_cmd3_0: u32,
    pub emc_cmd_mapping_cmd3_1: u32,
    pub emc_cmd_mapping_cmd3_2: u32,
    pub emc_cmd_mapping_byte: u32,

    pub emc_fbio_spare: u32,

    pub emc_cfg_rsv: u32,

    pub emc_mrs: u32,
    pub emc_emrs: u32,
    pub emc_emrs2: u32,
    pub emc_emrs3: u32,
    pub emc_mrw1: u32,
    pub emc_mrw2: u32,
    pub emc_mrw3: u32,
    pub emc_mrw4: u32,

    pub emc_mrw6: u32,
    pub emc_mrw8: u32,
    pub emc_mrw9: u32,
    pub emc_mrw10: u32,
    pub emc_mrw12: u32,
    pub emc_mrw13: u32,
    pub emc_mrw14: u32,

    pub emc_mrw_extra: u32,
    pub emc_warm_boot_mrw_extra: u32,
    pub emc_warm_boot_extramode_reg_write_enable: u32,
    pub emc_extramode_reg_write_enable: u32,

    pub emc_mrw_reset_command: u32,
    pub emc_mrw_reset_ninit_wait: u32,
    pub emc_mrs_wait_cnt: u32,
    pub emc_mrs_wait_cnt2: u32,

    pub emc_cfg: u32,
    pub emc_cfg2: u32,
    pub emc_cfg_pipe: u32,

    pub emc_cfg_pipe_clk: u32,
    pub emc_fdpd_ctrl_cmd_no_ramp: u32,
    pub emc_cfg_update: u32,

    pub emc_dbg: u32,

    pub emc_dbg_write_mux: u32,

    pub emc_cmd_q: u32,
    pub emc_mc2emc_q: u32,
    pub emc_dyn_self_ref_control: u32,

    pub ahb_arbitration_xbar_ctrl_meminit_done: u32,

    pub emc_cfg_dig_dll: u32,
    pub emc_cfg_dig_dll_1: u32,

    pub emc_cfg_dig_dll_period: u32,
    pub emc_dev_select: u32,

    pub emc_sel_dpd_ctrl: u32,

    pub emc_fdpd_ctrl_dq: u32,
    pub emc_fdpd_ctrl_cmd: u32,
    pub emc_pmacro_ib_vref_dq_0: u32,
    pub emc_pmacro_ib_vref_dq_1: u32,
    pub emc_pmacro_ib_vref_dqs_0: u32,
    pub emc_pmacro_ib_vref_dqs_1: u32,
    pub emc_pmacro_ib_rxrt: u32,
    pub emc_cfg_pipe1: u32,
    pub emc_cfg_pipe2: u32,

    pub emc_pmacro_quse_ddll_rank0_0: u32,
    pub emc_pmacro_quse_ddll_rank0_1: u32,
    pub emc_pmacro_quse_ddll_rank0_2: u32,
    pub emc_pmacro_quse_ddll_rank0_3: u32,
    pub emc_pmacro_quse_ddll_rank0_4: u32,
    pub emc_pmacro_quse_ddll_rank0_5: u32,
    pub emc_pmacro_quse_ddll_rank1_0: u32,
    pub emc_pmacro_quse_ddll_rank1_1: u32,
    pub emc_pmacro_quse_ddll_rank1_2: u32,
    pub emc_pmacro_quse_ddll_rank1_3: u32,
    pub emc_pmacro_quse_ddll_rank1_4: u32,
    pub emc_pmacro_quse_ddll_rank1_5: u32,

    pub emc_pmacro_ob_ddll_long_dq_rank0_0: u32,
    pub emc_pmacro_ob_ddll_long_dq_rank0_1: u32,
    pub emc_pmacro_ob_ddll_long_dq_rank0_2: u32,
    pub emc_pmacro_ob_ddll_long_dq_rank0_3: u32,
    pub emc_pmacro_ob_ddll_long_dq_rank0_4: u32,
    pub emc_pmacro_ob_ddll_long_dq_rank0_5: u32,
    pub emc_pmacro_ob_ddll_long_dq_rank1_0: u32,
    pub emc_pmacro_ob_ddll_long_dq_rank1_1: u32,
    pub emc_pmacro_ob_ddll_long_dq_rank1_2: u32,
    pub emc_pmacro_ob_ddll_long_dq_rank1_3: u32,
    pub emc_pmacro_ob_ddll_long_dq_rank1_4: u32,
    pub emc_pmacro_ob_ddll_long_dq_rank1_5: u32,

    pub emc_pmacro_ob_ddll_long_dqs_rank0_0: u32,
    pub emc_pmacro_ob_ddll_long_dqs_rank0_1: u32,
    pub emc_pmacro_ob_ddll_long_dqs_rank0_2: u32,
    pub emc_pmacro_ob_ddll_long_dqs_rank0_3: u32,
    pub emc_pmacro_ob_ddll_long_dqs_rank0_4: u32,
    pub emc_pmacro_ob_ddll_long_dqs_rank0_5: u32,
    pub emc_pmacro_ob_ddll_long_dqs_rank1_0: u32,
    pub emc_pmacro_ob_ddll_long_dqs_rank1_1: u32,
    pub emc_pmacro_ob_ddll_long_dqs_rank1_2: u32,
    pub emc_pmacro_ob_ddll_long_dqs_rank1_3: u32,
    pub emc_pmacro_ob_ddll_long_dqs_rank1_4: u32,
    pub emc_pmacro_ob_ddll_long_dqs_rank1_5: u32,

    pub emc_pmacro_ib_ddll_long_dqs_rank0_0: u32,
    pub emc_pmacro_ib_ddll_long_dqs_rank0_1: u32,
    pub emc_pmacro_ib_ddll_long_dqs_rank0_2: u32,
    pub emc_pmacro_ib_ddll_long_dqs_rank0_3: u32,
    pub emc_pmacro_ib_ddll_long_dqs_rank1_0: u32,
    pub emc_pmacro_ib_ddll_long_dqs_rank1_1: u32,
    pub emc_pmacro_ib_ddll_long_dqs_rank1_2: u32,
    pub emc_pmacro_ib_ddll_long_dqs_rank1_3: u32,

    pub emc_pmacro_ddll_long_cmd_0: u32,
    pub emc_pmacro_ddll_long_cmd_1: u32,
    pub emc_pmacro_ddll_long_cmd_2: u32,
    pub emc_pmacro_ddll_long_cmd_3: u32,
    pub emc_pmacro_ddll_long_cmd_4: u32,
    pub emc_pmacro_ddll_short_cmd_0: u32,
    pub emc_pmacro_ddll_short_cmd_1: u32,
    pub emc_pmacro_ddll_short_cmd_2: u32,

    pub warm_boot_wait: u32,

    pub emc_odt_write: u32,

    pub emc_zcal_interval: u32,
    pub emc_zcal_wait_cnt: u32,
    pub emc_zcal_mrw_cmd: u32,

    pub emc_mrs_reset_dll: u32,
    pub emc_zcal_init_dev0: u32,
    pub emc_zcal_init_dev1: u32,
    pub emc_zcal_init_wait: u32,
    pub emc_zcal_warm_cold_boot_enables: u32,

    pub emc_mrw_lpddr2zcal_warm_boot: u32,
    pub emc_zqcal_ddr3_warm_boot: u32,

    pub emc_zqcal_lpddr4_warm_boot: u32,

    pub emc_zcal_warm_boot_wait: u32,
    pub emc_mrs_warm_boot_enable: u32,
    pub emc_mrs_reset_dll_wait: u32,
    pub emc_mrs_extra: u32,
    pub emc_warm_boot_mrs_extra: u32,
    pub emc_emrs_ddr2_dll_enable: u32,
    pub emc_mrs_ddr2_dll_reset: u32,
    pub emc_emrs_ddr2_ocd_calib: u32,
    pub emc_ddr2_wait: u32,
    pub emc_clken_override: u32,
    pub emc_extra_refresh_num: u32,
    pub emc_clken_override_allwarm_boot: u32,
    pub mc_clken_override_allwarm_boot: u32,
    pub emc_cfg_dig_dll_period_warm_boot: u32,

    pub pmc_vddp_sel: u32,
    pub pmc_vddp_sel_wait: u32,
    pub pmc_ddr_pwr: u32,
    pub pmc_ddr_cfg: u32,
    pub pmc_io_dpd3_req: u32,
    pub pmc_io_dpd3_req_wait: u32,

    pub pmc_io_dpd4_req_wait: u32,

    pub pmc_reg_short: u32,
    pub pmc_no_io_power: u32,

    pub pmc_ddr_ctrl_wait: u32,
    pub pmc_ddr_ctrl: u32,

    pub emc_acpd_control: u32,

    pub emc_swizzle_rank0_byte0: u32,
    pub emc_swizzle_rank0_byte1: u32,
    pub emc_swizzle_rank0_byte2: u32,
    pub emc_swizzle_rank0_byte3: u32,
    pub emc_swizzle_rank1_byte0: u32,
    pub emc_swizzle_rank1_byte1: u32,
    pub emc_swizzle_rank1_byte2: u32,
    pub emc_swizzle_rank1_byte3: u32,

    pub emc_txdsrvttgen: u32,

    pub emc_data_brlshft0: u32,
    pub emc_data_brlshft1: u32,

    pub emc_dqs_brlshft0: u32,
    pub emc_dqs_brlshft1: u32,

    pub emc_cmd_brlshft0: u32,
    pub emc_cmd_brlshft1: u32,
    pub emc_cmd_brlshft2: u32,
    pub emc_cmd_brlshft3: u32,

    pub emc_quse_brlshft0: u32,
    pub emc_quse_brlshft1: u32,
    pub emc_quse_brlshft2: u32,
    pub emc_quse_brlshft3: u32,

    pub emc_dll_cfg0: u32,
    pub emc_dll_cfg1: u32,

    pub emc_pmc_scratch1: u32,
    pub emc_pmc_scratch2: u32,
    pub emc_pmc_scratch3: u32,

    pub emc_pmacro_pad_cfg_ctrl: u32,

    pub emc_pmacro_vttgen_ctrl0: u32,
    pub emc_pmacro_vttgen_ctrl1: u32,
    pub emc_pmacro_vttgen_ctrl2: u32,

    pub emc_pmacro_brick_ctrl_rfu1: u32,
    pub emc_pmacro_cmd_brick_ctrl_fdpd: u32,
    pub emc_pmacro_brick_ctrl_rfu2: u32,
    pub emc_pmacro_data_brick_ctrl_fdpd: u32,
    pub emc_pmacro_bg_bias_ctrl0: u32,
    pub emc_pmacro_data_pad_rx_ctrl: u32,
    pub emc_pmacro_cmd_pad_rx_ctrl: u32,
    pub emc_pmacro_data_rx_term_mode: u32,
    pub emc_pmacro_cmd_rx_term_mode: u32,
    pub emc_pmacro_data_pad_tx_ctrl: u32,
    pub emc_pmacro_common_pad_tx_ctrl: u32,
    pub emc_pmacro_cmd_pad_tx_ctrl: u32,
    pub emc_cfg3: u32,

    pub emc_pmacro_tx_pwrd0: u32,
    pub emc_pmacro_tx_pwrd1: u32,
    pub emc_pmacro_tx_pwrd2: u32,
    pub emc_pmacro_tx_pwrd3: u32,
    pub emc_pmacro_tx_pwrd4: u32,
    pub emc_pmacro_tx_pwrd5: u32,

    pub emc_config_sample_delay: u32,

    pub emc_pmacro_brick_mapping0: u32,
    pub emc_pmacro_brick_mapping1: u32,
    pub emc_pmacro_brick_mapping2: u32,

    pub emc_pmacro_tx_sel_clk_src0: u32,
    pub emc_pmacro_tx_sel_clk_src1: u32,
    pub emc_pmacro_tx_sel_clk_src2: u32,
    pub emc_pmacro_tx_sel_clk_src3: u32,
    pub emc_pmacro_tx_sel_clk_src4: u32,
    pub emc_pmacro_tx_sel_clk_src5: u32,

    pub emc_pmacro_ddll_bypass: u32,

    pub emc_pmacro_ddll_pwrd0: u32,
    pub emc_pmacro_ddll_pwrd1: u32,
    pub emc_pmacro_ddll_pwrd2: u32,

    pub emc_pmacro_cmd_ctrl0: u32,
    pub emc_pmacro_cmd_ctrl1: u32,
    pub emc_pmacro_cmd_ctrl2: u32,

    pub mc_emem_adr_cfg: u32,
    pub mc_emem_adr_cfg_dev0: u32,
    pub mc_emem_adr_cfg_dev1: u32,

    pub mc_emem_adr_cfg_channel_mask: u32,

    pub mc_emem_adr_cfg_bank_mask0: u32,
    pub mc_emem_adr_cfg_bank_mask1: u32,
    pub mc_emem_adr_cfg_bank_mask2: u32,

    pub mc_emem_cfg: u32,

    pub mc_emem_arb_cfg: u32,
    pub mc_emem_arb_outstanding_req: u32,

    pub emc_emem_arb_refpb_hp_ctrl: u32,
    pub emc_emem_arb_refpb_bank_ctrl: u32,

    pub mc_emem_arb_timing_rcd: u32,
    pub mc_emem_arb_timing_rp: u32,
    pub mc_emem_arb_timing_rc: u32,
    pub mc_emem_arb_timing_ras: u32,
    pub mc_emem_arb_timing_faw: u32,
    pub mc_emem_arb_timing_rrd: u32,
    pub mc_emem_arb_timing_rap2pre: u32,
    pub mc_emem_arb_timing_wap2pre: u32,
    pub mc_emem_arb_timing_r2r: u32,
    pub mc_emem_arb_timing_w2w: u32,
    pub mc_emem_arb_timing_r2w: u32,
    pub mc_emem_arb_timing_w2r: u32,

    pub mc_emem_arb_timing_rfcpb: u32,

    pub mc_emem_arb_da_turns: u32,
    pub mc_emem_arb_da_covers: u32,
    pub mc_emem_arb_misc0: u32,
    pub mc_emem_arb_misc1: u32,
    pub mc_emem_arb_misc2: u32,

    pub mc_emem_arb_ring1_throttle: u32,
    pub mc_emem_arb_override: u32,
    pub mc_emem_arb_override1: u32,
    pub mc_emem_arb_rsv: u32,

    pub mc_da_cfg0: u32,
    pub mc_emem_arb_timing_ccdmw: u32,

    pub mc_clken_override: u32,

    pub mc_stat_control: u32,
    pub mc_video_protect_bom: u32,
    pub mc_video_protect_bom_adr_hi: u32,
    pub mc_video_protect_size_mb: u32,
    pub mc_video_protect_vpr_override: u32,
    pub mc_video_protect_vpr_override1: u32,
    pub mc_video_protect_gpu_override0: u32,
    pub mc_video_protect_gpu_override1: u32,
    pub mc_sec_carveout_bom: u32,
    pub mc_sec_carveout_adr_hi: u32,
    pub mc_sec_carveout_size_mb: u32,
    pub mc_video_protect_write_access: u32,
    pub mc_sec_carveout_protect_write_access: u32,

    pub mc_generalized_carveout1_bom: u32,
    pub mc_generalized_carveout1_bom_hi: u32,
    pub mc_generalized_carveout1_size_128kb: u32,
    pub mc_generalized_carveout1_access0: u32,
    pub mc_generalized_carveout1_access1: u32,
    pub mc_generalized_carveout1_access2: u32,
    pub mc_generalized_carveout1_access3: u32,
    pub mc_generalized_carveout1_access4: u32,
    pub mc_generalized_carveout1_force_internal_access0: u32,
    pub mc_generalized_carveout1_force_internal_access1: u32,
    pub mc_generalized_carveout1_force_internal_access2: u32,
    pub mc_generalized_carveout1_force_internal_access3: u32,
    pub mc_generalized_carveout1_force_internal_access4: u32,
    pub mc_generalized_carveout1_cfg0: u32,

    pub mc_generalized_carveout2_bom: u32,
    pub mc_generalized_carveout2_bom_hi: u32,
    pub mc_generalized_carveout2_size_128kb: u32,
    pub mc_generalized_carveout2_access0: u32,
    pub mc_generalized_carveout2_access1: u32,
    pub mc_generalized_carveout2_access2: u32,
    pub mc_generalized_carveout2_access3: u32,
    pub mc_generalized_carveout2_access4: u32,
    pub mc_generalized_carveout2_force_internal_access0: u32,
    pub mc_generalized_carveout2_force_internal_access1: u32,
    pub mc_generalized_carveout2_force_internal_access2: u32,
    pub mc_generalized_carveout2_force_internal_access3: u32,
    pub mc_generalized_carveout2_force_internal_access4: u32,
    pub mc_generalized_carveout2_cfg0: u32,

    pub mc_generalized_carveout3_bom: u32,
    pub mc_generalized_carveout3_bom_hi: u32,
    pub mc_generalized_carveout3_size_128kb: u32,
    pub mc_generalized_carveout3_access0: u32,
    pub mc_generalized_carveout3_access1: u32,
    pub mc_generalized_carveout3_access2: u32,
    pub mc_generalized_carveout3_access3: u32,
    pub mc_generalized_carveout3_access4: u32,
    pub mc_generalized_carveout3_force_internal_access0: u32,
    pub mc_generalized_carveout3_force_internal_access1: u32,
    pub mc_generalized_carveout3_force_internal_access2: u32,
    pub mc_generalized_carveout3_force_internal_access3: u32,
    pub mc_generalized_carveout3_force_internal_access4: u32,
    pub mc_generalized_carveout3_cfg0: u32,

    pub mc_generalized_carveout4_bom: u32,
    pub mc_generalized_carveout4_bom_hi: u32,
    pub mc_generalized_carveout4_size_128kb: u32,
    pub mc_generalized_carveout4_access0: u32,
    pub mc_generalized_carveout4_access1: u32,
    pub mc_generalized_carveout4_access2: u32,
    pub mc_generalized_carveout4_access3: u32,
    pub mc_generalized_carveout4_access4: u32,
    pub mc_generalized_carveout4_force_internal_access0: u32,
    pub mc_generalized_carveout4_force_internal_access1: u32,
    pub mc_generalized_carveout4_force_internal_access2: u32,
    pub mc_generalized_carveout4_force_internal_access3: u32,
    pub mc_generalized_carveout4_force_internal_access4: u32,
    pub mc_generalized_carveout4_cfg0: u32,

    pub mc_generalized_carveout5_bom: u32,
    pub mc_generalized_carveout5_bom_hi: u32,
    pub mc_generalized_carveout5_size_128kb: u32,
    pub mc_generalized_carveout5_access0: u32,
    pub mc_generalized_carveout5_access1: u32,
    pub mc_generalized_carveout5_access2: u32,
    pub mc_generalized_carveout5_access3: u32,
    pub mc_generalized_carveout5_access4: u32,
    pub mc_generalized_carveout5_force_internal_access0: u32,
    pub mc_generalized_carveout5_force_internal_access1: u32,
    pub mc_generalized_carveout5_force_internal_access2: u32,
    pub mc_generalized_carveout5_force_internal_access3: u32,
    pub mc_generalized_carveout5_force_internal_access4: u32,
    pub mc_generalized_carveout5_cfg0: u32,

    pub emc_ca_training_enable: u32,
    pub swizzle_rank_byte_encode: u32,
    pub boot_rom_patch_control: u32,
    pub boot_rom_patch_data: u32,

    pub mc_mts_carveout_bom: u32,
    pub mc_mts_carveout_adr_hi: u32,
    pub mc_mts_carveout_size_mb: u32,
    pub mc_mts_carveout_reg_ctrl: u32,
}
